services:
  website:
    restart: always
    container_name: tiffanys-website
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/usr/share/nginx/html
      